# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages: 
- stage: dev
  jobs:
  - job: PhaseA  
    pool: default
    steps:
    - script: echo Hello, dev!
      displayName: 'Run a one-line script'

    - script: echo $(variable)

  - job: PhaseB
    pool: default
    steps:
    - script: SET

    variables:
    - name: variable
      value: job

  variables:
    - name: variable
      value: devstage

- stage: prod
  jobs:
  - job: PhaseB 
    pool: default
    steps:
    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo exec prc_SetRegistryValue 1, '#\FeatureAvailability\Entries\DistributedTask.EnableStages\AvailabilityState\', '1' 
        ping google.com -n 1
      displayName: 'Run a multi-line script'

  - job: PhaseA
    pool: default
    steps:
    - script: echo $(variable)

  variables:
    - name: variable
      value: prodstage
