# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: PhaseA
    pool: server
    steps:
      - task: Delay@1
        displayName: 'Delay by 1 minutes'
        inputs:
          delayForMinutes: 1